### ISSUE TITLE
Can't Run homebridge after fresh install

### ISSUE THREAD

**Issue by spjt1502** [rooi/homebridge-lightwaverf#32]
Hi I had been running homebridge with no issues for over a year until this week when my RPi's SD card became corrupted, I have replaced it and install a fresh copy of raspbian and followed all the steps as before.

my first test plugin was the wemo accessory and this works with no issues, i then added the lighwavrf plugin and thats where things go horribly wrong!

i had kept a copy of my config.json file so i know that it works and is error free however this is the response i now get when starting homebridge

[8/18/2017, 11:16:46 AM] [LightWaveRF] Initializing platform accessory 'Lounge Paper Lamp'...
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:76
      throw new Error("Cannot add a Characteristic with the same UUID as another Characteristic in this Service: " + existing.UUID);
      ^

Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000052-0000-1000-8000-0026BB765291
    at Service.AccessoryInformation.Service.addCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:76:13)
    at LightWaveRFAccessory.getServices (/usr/lib/node_modules/homebridge-lightwaverf/index.js:437:4)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:364:32)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at getLights (/usr/lib/node_modules/homebridge-lightwaverf/index.js:131:15)
    at LightWaveRFPlatform.accessories (/usr/lib/node_modules/homebridge-lightwaverf/index.js:137:5)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)

im really at a loss of what to do next so any help would be great.

its so annoying as the homebridge was working perfectly until this issue.

**Comment by Cardo1** [comment]
Did you copy over the entire homebridge config directory? If so, it may be worth deleting the accessories directory and maybe the persist directory and see what happens.

**Comment by spjt1502** [comment]
no just the config.json file
