### ISSUE TITLE
Startup Problems

### ISSUE THREAD

**Issue by LodanUK** [rooi/homebridge-lightwaverf#36]
Sorry managed to fix part myself

**Comment by LodanUK** [comment]
Actually the beauty of posting is I spent ages looking beforehand with no joy but as soon as I posted I think I have gotten a little further.  I was missing some things in my config.json.  Now my config.json looks like this (which I beleive is correct for a post 2016 lightwave link)

{
        "bridge": {
                "name": "Homebridge",
                "username": "B8:27:EB:C8:81:39",
                "port": 51826,
                "pin": "031-45-154"
        },

        "platforms": [{
                "platform": "LightWaveRF",
                "name": "LightWaveRF",
                "ip_address": "192.168.0.139",
                "devices": [{
                                "roomId": 1,
                                "roomName": "Office",
                                "deviceId": 1,
                                "deviceName": "Cinema",
                                "deviceType": "D"
                        },
                        {
                                "roomId": 1,
                                "roomName": "Office",
                                "deviceId": 2,
                                "deviceName": "Office",
                                "deviceType": "D"
                        },
                        {
                                "roomId": 1,
                                "roomName": "Office",
                                "deviceId": 3,
                                "deviceName": "Middle",
                                "deviceType": "D"
                        }
                ]
        }]
}

That now gives me this:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-2-22 11:17:25] Loaded plugin: homebridge-lightwaverf
[2018-2-22 11:17:25] Registering platform 'homebridge-lightwaverf.LightWaveRF'
[2018-2-22 11:17:25] ---
[2018-2-22 11:17:25] Loaded config.json with 0 accessories and 1 platforms.
[2018-2-22 11:17:25] ---
[2018-2-22 11:17:25] Loading 1 platforms...
[2018-2-22 11:17:25] [LightWaveRF] Initializing LightWaveRF platform...
[2018-2-22 11:17:25] [LightWaveRF] LightWaveRF Platform Plugin Version 0.1.5
**[2018-2-22 11:17:25] [LightWaveRF] Fetching LightWaveRF switches and dimmers...
No email or pin specified. The server configuration (rooms, devices, etc.) cannot be obtained**
device =
{ roomId: 1,
  roomName: 'Office',
  deviceId: 1,
  deviceName: 'Cinema',
  deviceType: 'D' }
device =
{ roomId: 1,
  roomName: 'Office',
  deviceId: 2,
  deviceName: 'Office',
  deviceType: 'D' }
device =
{ roomId: 1,
  roomName: 'Office',
  deviceId: 3,
  deviceName: 'Middle',
  deviceType: 'D' }
[2018-2-22 11:17:25] [LightWaveRF] Initializing platform accessory 'Office Cinema'...
[2018-2-22 11:17:25] [LightWaveRF] Initializing platform accessory 'Office Office'...
[2018-2-22 11:17:26] [LightWaveRF] Initializing platform accessory 'Office Middle'...
Setup Payload:
X-HM://0023ISYWY173G
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

Receiver socket listening 0.0.0.0:9761
/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at new Advertisement (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:47:30)
    at Bridge.Accessory._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:661:20)
    at emitOne (events.js:116:13)
    at HAPServer.emit (events.js:211:7)
    at HAPServer._onListening (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:116:13)
    at EventedHTTPServer.emit (events.js:211:7)
    at EventedHTTPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)

I think the bit where it is asking me for an email pin is for the pre 2016 systems and I just need to find a way to pair it.  It also looks like I have found myself a new error at the bottom.
