### ISSUE TITLE
won't recognise the lightwave plugin

### ISSUE THREAD

**Issue by gshoebridge** [rooi/homebridge-lightwaverf#38]
Ive tried multiple times to load the plugin but keep getting the following error; 

      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'LightwaveRF' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

Any help here please

**Comment by rooi** [comment]
Could you try if instalation with aleviated priviliges works?

sudo npm install -g homebridge-lightwaverf

**Comment by gshoebridge** [comment]
Thank you

Managed to get it sorted - used the command UI which applied all privelidges properly and everything working like a dream.
Homebridge seems to work well if not a little simple at the moment (that’s the HomeKit limitation not HB)



Kind regards

Guy Shoebridge

Sent from my iPhone

On 23 Mar 2018, at 14:41, rooi <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you try if instalation with aleviated priviliges works?

sudo npm install -g homebridge-lightwaverf
